spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room_rental
    username: root
    password: tdhuy0909
  jpa:
    hibernate:
      ddl-auto: update # Chạy local tạm thời, khi nào lên production thì đổi thành validate và dùng Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.MySQLDialect"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_CLIENT_SECRET}
            scope:
              - email
              - profile
server:
  port: 8080

app:
  jwtSecret: ${JWT_SECRET:dGhodXkwOTA5MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6}
  jwtExpirationMs: 86400000
